### ISSUE TITLE
Boob Wars: Big Boobs vs Flat Chests Update Support 

### ISSUE THREAD

**Issue by Lebedev30** [crskycode/KrkrDump#11]
CreateProcess failed : The operation identifier is not valid.

Please include support if possible in future release

**Comment by crskycode** [comment]
Use GARbro instead. Choose `MadoCrypt` encryption algorithm. For example: `Namaiki Delation`.

**Comment by Lebedev30** [comment]
Thank you very much. Finally managed to decode the files and there will be an uncensored version.
