### ISSUE TITLE
想问一下提取到的.ks.scn被加密的问题

### ISSUE THREAD

**Issue by sakura-umi** [crskycode/KrkrDump#4]
游戏：RIDDLE JOKER steam官中版

使用GARbro解包获得的xxx.ks.scn文件在使用psbdecompile反编译时会报以下错误：
![image](https://github.com/crskycode/KrkrDump/assets/56287117/cab7dfb0-11a5-4001-9d31-78bbac0fdce1)

但使用KrkrDump获取到的xxx.ks.scn可以直接通过psbdecompile进行处理，不需要给定key

想问一下这里面的区别，以及是否能找到加密ks.scn文件的解密密钥的方法，非常感谢！

p.s. 附例（不支持ks.scn格式上传，只能先打包成zip）

GARbro提取版：[000.プロローグver1.10.ks.scn.zip](https://github.com/crskycode/KrkrDump/files/11871488/000.ver1.10.ks.scn.zip)
KrkrDump提取版：[000.プロローグver1.10.ks.scn.zip](https://github.com/crskycode/KrkrDump/files/11871506/000.ver1.10.ks.scn.zip)

**Comment by crskycode** [comment]
1. GARbro那边的Key选错（或者不正确）导致解密失败。
2. KrkrDump提取文件时提取的是游戏内解密好的文件。

**Comment by sakura-umi** [comment]
> * GARbro那边的Key选错（或者不正确）导致解密失败。
> * KrkrDump提取文件时提取的是游戏内解密好的文件。

感谢回复！

但GARbro那边我选的是对应的key，且解包出来的其他文件包括音频CG什么的都能看，就只有.ks.scn提取出来之后是加密的，感觉貌似不太应该是key选错的问题
