### ISSUE TITLE
提取steam游戏时游戏启动失败

### ISSUE THREAD

**Issue by dogdie233** [crskycode/KrkrDump#6]
当我将steam版的千恋万花拖入KrkrDump时  
游戏启动弹出了Steam Error弹窗，内容是Application load error: 3:0000065432  
日志只有四行
```
KrkrDump Startup
Game Executable Path = "的确是全英文的"
Image Base = 00FA0000
Image Base = 504000
```

**Comment by crskycode** [comment]
Steam 游戏是有保护的，KrkrDump 目前不支持越过保护来提取文件，你需要去找一个别人处理过的版本来提取。

**Comment by dogdie233** [comment]
嗯我解决了，用steamless处理一下就好了，谢谢
