### ISSUE TITLE
关于解包路径的问题

### ISSUE THREAD

**Issue by CsVeryLoveXieWenLi** [crskycode/KrkrDump#7]
**目前我试了，输出路径并不会更详细。从哪个xp3封包里面解包出来，无法得知。**

**虽然像 "startup.tjs"，这种固定位置的，但是通过资源猜位置未免太麻烦了。**

**能否添加更详细的路径输出呢？我觉得我的问题多此一举了，能实现早实现了，我研究一下。**

**这样可以更方便的进行封包，虽然也有像KirikiriTools这样的工具，更详细总是好的，拥有了更多选择。**

**Comment by CsVeryLoveXieWenLi** [comment]
**如果我的问题是多此一举的，我感到很抱歉。**

**Comment by crskycode** [comment]
你说得对，实现思路也不是没有，如果你能研究清楚其中的逻辑，并且提一个PR实现，我会非常感谢你。

**Comment by CsVeryLoveXieWenLi** [comment]
**好的，谢谢您回复我，我会努力的，我已经看清一点逻辑了。**

> 你说得对，实现思路也不是没有，如果你能研究清楚其中的逻辑，并且提一个PR实现，我会非常感谢你。

**Comment by CsVeryLoveXieWenLi** [comment]
**感觉我没辙了，明天再弄弄看。**

**Comment by CsVeryLoveXieWenLi** [comment]
**确实可以区分，但是路径真的是真实的么，我解包KRKR手机移植的，文件夹对不上。**

**而且缺TJS，运行不上，不知道怎么弄了，明天继续。**

**Comment by CsVeryLoveXieWenLi** [comment]
**每次读取密文，就代表下次必是明文。**

<img width="1280" alt="image" src="https://github.com/crskycode/KrkrDump/assets/102389677/a5201f08-b5dd-479c-8238-e1ee4e6c2e44">

[KrkrDump-2024-01-30.log](https://github.com/crskycode/KrkrDump/files/14097281/KrkrDump-2024-01-30.log)

**Comment by CsVeryLoveXieWenLi** [comment]
**封包内的路径是被破坏了还是如何，我不理解，KRKR移植的封包内部更有细分文件夹。**
